mads.exe UFOSLALOM.ASM -d:EASY -o:UFOSLALOM_EASY.XEX -t:UFOSLALOM_EASY.lab -l:UFOSLALOM_EASY.lst
mads.exe UFOSLALOM.ASM -d:NORMAL -o:UFOSLALOM_NORMAL.XEX -t:UFOSLALOM_NORMAL.lab -l:UFOSLALOM_NORMAL.lst
mads.exe UFOSLALOM.ASM -d:HARD -o:UFOSLALOM_HARD.XEX -t:UFOSLALOM_HARD.lab -l:UFOSLALOM_HARD.lst
